# SPDX-FileCopyrightText: 2024 SeisSol Group
# 
# SPDX-License-Identifier: BSD-3-Clause

version = 1

[[annotations]]
path = ["**/*.xml", "**/*.json"]
SPDX-FileCopyrightText = "2012-2024 SeisSol Group"
SPDX-License-Identifier = "BSD-3-Clause"
