# SPDX-FileCopyrightText: 2025 SeisSol Group
# 
# SPDX-License-Identifier: BSD-3-Clause

version = 1

[[annotations]]
path = ["ISSUE_TEMPLATE/*.md"]
SPDX-FileCopyrightText = "2019-2024 SeisSol Group"
SPDX-License-Identifier = "BSD-3-Clause"
