# SPDX-FileCopyrightText: 2024 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause

name: build-seissol-gpu
on:
  - push

jobs:
  seissol:
    name: seissol
    runs-on: ubuntu-24.04
    container: ${{ matrix.setup.container }}
    strategy:
      fail-fast: false
      matrix:
        order:
          - 6
        arch:
          - hsw
        build_type:
          - Release
          - Debug
        equation:
          - elastic
          - anisotropic
        precision:
          - single
          - double
        setup:
          - arch: sm_60
            backend: cuda
            syclcc: acpp
            cc: gcc-13
            cxx: g++-13
            fc: gfortran-13
            container: seissol/gha-gpu-nv:davschneller-gpu-image
          - arch: sm_60
            backend: cuda
            syclcc: acpp
            cc: clang-18
            cxx: clang++-18
            fc: gfortran-13 # TODO?
            container: seissol/gha-gpu-nv:davschneller-gpu-image
          - arch: sm_60
            backend: cuda
            syclcc: acpp
            cc: nvc
            cxx: nvc++
            fc: nvfortran
            container: seissol/gha-gpu-nvhpc:davschneller-gpu-image
          - arch: gfx906
            backend: hip
            syclcc: acpp
            cc: gcc-13
            cxx: g++-13
            fc: gfortran-13
            container: seissol/gha-gpu-amd:davschneller-gpu-image
          - arch: gfx906
            backend: hip
            syclcc: acpp
            cc: clang-18
            cxx: clang++-18
            fc: gfortran-13 # TODO?
            container: seissol/gha-gpu-amd:davschneller-gpu-image
          - arch: skl
            backend: oneapi
            syclcc: dpcpp
            cc: icx
            cxx: icpx
            fc: ifx
            container: seissol/gha-gpu-intel:davschneller-gpu-image
    steps:
      - name: checkout-seissol
        uses: actions/checkout@v4

      - id: build
        name: build-seissol
        run: |
          git config --global --add safe.directory '*'
          git submodule update --init --recursive
          mkdir build && cd build
          if [ "${{ matrix.equation }}" = viscoelastic2 ]; then
              mechanisms=3
          else
              mechanisms=0
          fi

          # TODO: change to `-Wall -Werror` at some point
          EXTRA_FLAGS="-Wall"

          # FIXME: hotfix. Needs to be fixed in SeisSol itself
          export HIP_PATH=/opt/rocm

          export CFLAGS="${EXTRA_FLAGS} ${CFLAGS}"
          export CXXFLAGS="${EXTRA_FLAGS} ${CXXFLAGS}"
          export FFLAGS="${EXTRA_FLAGS} ${FFLAGS}"

          export CC=${{matrix.setup.cc}}
          export CXX=${{matrix.setup.cxx}}
          export FC=${{matrix.setup.fc}}

          cmake .. -GNinja -DTESTING=OFF -DDEVICE_BACKEND=${{matrix.setup.backend}} -DDEVICE_ARCH=${{matrix.setup.arch}} -DSYCL_CC=${{matrix.setup.syclcc}} -DHOST_ARCH=${{matrix.arch}} -DORDER=${{matrix.order}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DEQUATIONS=${{matrix.equation}} -DPRECISION=${{matrix.precision}} -DNUMBER_OF_MECHANISMS=$mechanisms
          ninja
