name: clang-format
on:
  - push

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get -y install python3

          # use once clang-19 or higher is needed
          # wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          # sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-18 main"
          # sudo add-apt-repository "deb-src http://apt.llvm.org/noble/ llvm-toolchain-noble-18 main"
          # sudo apt-get update

          sudo apt-get -y install clang-format-18

      - name: run-clang-format
        run: |
          set -euo pipefail
          clang-format-18 --version
          which clang-format-18
          ./.ci/format.sh $(which clang-format-18) .
          git diff > formatting.patch
          cat formatting.patch 
          if [ -s ./formatting.patch ]; then (exit 176); fi
