# SPDX-FileCopyrightText: 2025 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause

name: reuse
on:
  - push

jobs:
  reuse:
    name: reuse
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v4
